<%@ taglib uri="/WEB-INF/tld/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/tld/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/tld/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/tld/struts-nested.tld" prefix="nested" %>
<%@ taglib uri="/WEB-INF/tld/struts-html-el.tld" prefix="html-el" %>
<%@ taglib uri="/WEB-INF/tld/struts-bean-el.tld" prefix="bean-el" %>
<%@ taglib uri="/WEB-INF/tld/struts-logic-el.tld" prefix="logic-el" %>
<%@ taglib uri="/WEB-INF/tld/c.tld" prefix="c" %>
<%@ taglib uri="/WEB-INF/tld/fmt.tld" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/tld/x.tld" prefix="x" %>
<%@ taglib uri="/WEB-INF/tld/taglibs-string.tld" prefix="str" %>
<%@ taglib uri="/WEB-INF/tld/claros-tabview.tld" prefix="tab" %>
<%@ taglib uri="/WEB-INF/tld/claros-paginator.tld" prefix="page" %>
